export const types = {
    SET_LEVEL: 'SET_LEVEL',
    GET_USER_DATA_BY_EMAIL: 'GET_USER_DATA_BY_EMAIL',
    GET_GROUP_DATA_TABLE: 'GET_GROUP_DATA_TABLE',
    GET_GROUP_DATA_IMAGE: 'GET_GROUP_DATA_IMAGE'
};
